#!/bin/bash

# Utworzenie pliku wymiany
sudo fallocate -l 10G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

# Konfiguracja parametrów systemowych
echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
echo 'vm.vfs_cache_pressure=50' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

# Zamontowanie pliku wymiany
sudo swapon -a

# Aktualizacja serwerów DNS
echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
echo "nameserver 1.0.0.1" | sudo tee -a /etc/resolv.conf

# Aktualizacja systemu
sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y
sudo apt clean
sudo updatedb
sudo systemctl restart systemd-journald

# Instalacja EasyPanel
curl -sSL https://get.easypanel.io | sh

# Restart serwera
sudo reboot
